### ISSUE TITLE
c++에서 size 와 length 의 차이가 무엇인가요???

### ISSUE THREAD

**Issue by hochan222** [HoHyun-Codong/algorithm#1]
c++에서 size 와 length 의 차이가 무엇인가요???

**Comment by juthor** [comment]
https://stackoverflow.com/questions/31628940/which-is-faster-c-string-length-or-size/31629030
https://stackoverflow.com/questions/905479/stdstring-length-and-size-member-functions

size()와 length()는 low.com/questions/31628940/which-is-faster-c-string-length-or-size/31629030
https://stackoverflow.com/questions/905479/stdstring-length-and-size-member-functions

size()와 length()는 각각 size와 크기를 반환하는데, 같은 string입력값이 제공되면 동일한 값으로 반환됩니다.
다만 length()하면 문자열 길이의 느낌이고 size는 vector 등에서의 크기 느낌이 강해서 상황에 따라 다르게 사용한다고 합니다.

**Comment by hochan222** [comment]
https://en.cppreference.com/w/cpp/string/basic_string/size
둘이 문서도 같이 공유하는군요! 거의 똑같은데 약간 역사적 차이군요..!
확인하고 문제 없으면 이슈 닫아주세요!
