### ISSUE TITLE
[칸반보드] 칸반보드 추가

### ISSUE THREAD

**Issue by hochan222** [HoHyun-Codong/algorithm#3]
칸반보드를 추가했어요! 위에 Projects에 이제 현재 진행 이슈를 시각적으로 볼수 있습니다!  

![image](https://user-images.githubusercontent.com/22424891/87890975-74ed9b00-ca73-11ea-99bf-51d8ecec5ff2.png)

1. 기획 / 신규 Issue
- 발생한 이슈들 나열
- 이슈 생성 시 자동으로 등록

2. 오류 및 문제사항 발견
- 오류 발견시 발생한 이슈들 나열
- 수동으로 등록

3. 진행 중 / 코드 작성 중
- PR 등록전인 작업 시작한 것들 나열
- 수동으로 등록

4. PR완료 / 리뷰 대기중
- PR 완료 후 1명의 리뷰를 기다리는 이슈 나열
- PR후 자동 등록
- 리뷰어 1명의 승인을 받았지만 아직 Merge 하지 않은 이슈
- 리뷰어 승인 완료시 자동 등록

6. Merge 완료 / Issue 종결
- Merge 완료된 이슈 또는 종결된 이슈
- 자동으로 등록

- - -

자동 등록 설정 완료

**Comment by hochan222** [comment]
PR은 pull request인데 지금은 아직 안하고 나중에 하니까 그냥 넘어가도 될것같아요!

**Comment by hochan222** [comment]
이슈 잘 정리돼있어서 링크 달았어요!
https://github.com/cheese10yun/github-project-management

**Comment by juthor** [comment]
네! 알겠습니다. 이슈 등록해 주셔서 감사합니다!
