### ISSUE TITLE
Git push가 안되는 경우 (fatal: refusing to merge unrelated histories)

### ISSUE THREAD

**Issue by juthor** [HoHyun-Codong/algorithm#4]
https://gdtbgl93.tistory.com/63

git pull origin 브런치명 --allow-unrelated-histories 을 통해서 해결할 수 있습니다.   
해당 명령어는 git에서는 서로 관련 기록이 없는 이질적인 두 프로젝트를 병합할 때 기본적으로 거부하는데, 이것을 허용해 주는 것이라고 합니다.

**Comment by hochan222** [comment]
제가 push해서 원격 깃허브 소스하고 현주님 개인 컴퓨터 소스하고 차이가 났군요!

**Comment by hochan222** [comment]
이슈 닫을게요 :)
